[package]
org = "ballerina"
name = "udp"
version = "1.4.1"
authors = ["Ballerina"]
keywords = ["UDP", "datagram", "transport"]
repository = "https://github.com/ballerina-platform/module-ballerina-udp"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.2.0"

[[platform.java11.dependency]]
groupId = "io.ballerina.stdlib"
artifactId = "udp-native"
version = "1.4.1"
path = "../native/build/libs/udp-native-1.4.1-SNAPSHOT.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/udp-test-utils-1.4.1-SNAPSHOT.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/netty-handler-4.1.100.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-buffer-4.1.100.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-transport-4.1.100.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-common-4.1.100.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-resolver-4.1.100.Final.jar"
