[package]
org = "ballerina"
name = "udp"
version = "1.2.2"
authors = ["Ballerina"]
keywords = ["UDP", "datagram", "transport"]
repository = "https://github.com/ballerina-platform/module-ballerina-udp"
icon = "icon.png"
license = ["Apache-2.0"]
distribution = "2201.0.4"

[[platform.java11.dependency]]
path = "../native/build/libs/udp-native-1.2.2.jar"

[[platform.java11.dependency]]
path = "../test-utils/build/libs/udp-test-utils-1.2.2.jar"
scope = "testOnly"

[[platform.java11.dependency]]
path = "./lib/netty-handler-4.1.77.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-buffer-4.1.77.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-transport-4.1.77.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-common-4.1.77.Final.jar"

[[platform.java11.dependency]]
path = "./lib/netty-resolver-4.1.77.Final.jar"
